config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :images
  resource :images do
    member do
      get 'show_image'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  def index
    @images = Image.limit 20
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    upload_file = image_params[:file]
    upload_to_s3 = image_params[:S3]
    image = {}

    if upload_file != nil
      image[:filename] = upload_file.original_filename
      image[:file] = upload_file.read
      image[:S3] = upload_to_s3
    end

    @image = Image.new image

    p @image

    if @image.save
      flash[:success] = "画像を保存しました！"
      p @image
      redirect_to "/"
    else
      flash[:error] = "画像を保存できませんでした.."
    end
  end

  def show_image
    @image = Image.find(params[:id])
    send_data @image.file, :type=>'image/jpeg', :disposition => 'inline'
  end


  private

  def image_params
    params.require(:image).permit :filename, :file, :S3

  end


end

app/controllers/top_controller.rb
class TopController < ApplicationController

def index
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/images/index.html.erb
<% @images.each do |img| %>
  <%= image_tag show_image_path(img), class: "middle-img" %>
<%= end %>

app/views/images/new.html.erb
<%= form_for(@image) do |f| %>
  <%= f.file_field :file, accept: "image/jpeg" %>
  <%= f.check_box :S3 %>
  <%= label_tag :S3, 'upload to AMAZON S3' %>
  <%= f.submit "upload" %>
<% end %>

app/views/images/show.html.erb
<%= image_tag show_image_path(@image), class: "large-img" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestRailsPaperclipS3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/top/index.html.erb
<%= link_to 'アップロード', :controller => 'images', :action => 'new' %>
<% Image.all.each do |image| %>
  <p>
    <%= image.id %>
    S3:<%= image.S3 %>
    <%= link_to image.filename, "images/show_image?id=#{image.id}",data: { no_turbolink: true } %>
  </p>
<% end %>